# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 12:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=250, verbose_name=b'Title')),
                ('adiscription', models.CharField(max_length=500, verbose_name=b'Description')),
                ('acategory', models.CharField(choices=[(b'LEARNING AND DEVELOPMENT', b'learning and development'), (b'CONFERENCES', b'conference'), (b'COMMUNICATION', b'communication'), (b'MOTIVATION', b'motivation'), (b'LEADERSHIP', b'leadership'), (b'EDUCATION', b'education'), (b'BUSINESS', b'business'), (b'NETWORKING', b'networking'), (b'ORGANIZATION', b'organization'), (b'MEETUPS', b'meetups'), (b'CREATIVITY AND INNOVATION', b'creativity and innovation'), (b'MANAGEMENT', b'management'), (b'INFORMATION TECHNOLOGY', b'information technology'), (b'OPERATIONS', b'operations'), (b'CONSULTING', b'consulting'), (b'FINANCE', b'finance'), (b'HUMAN RESOURCES', b'human resources'), (b'MANUFACTURING', b'manufacturing')], default=0, max_length=100, verbose_name=b'Category')),
                ('apicture', models.FileField(upload_to=b'', verbose_name=b'Upload Image')),
                ('apublish', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=250, verbose_name=b'Name')),
                ('cmobile', models.IntegerField(default=0, verbose_name=b'Mobile')),
                ('corganisation', models.CharField(max_length=250, verbose_name=b'Organisation')),
                ('cdesignation', models.CharField(max_length=500, verbose_name=b'Designation')),
                ('ccategory', models.CharField(choices=[(b'LEARNING AND DEVELOPMENT', b'learning and development'), (b'CONFERENCES', b'conference'), (b'COMMUNICATION', b'communication'), (b'MOTIVATION', b'motivation'), (b'LEADERSHIP', b'leadership'), (b'EDUCATION', b'education'), (b'BUSINESS', b'business'), (b'NETWORKING', b'networking'), (b'ORGANIZATION', b'organization'), (b'MEETUPS', b'meetups'), (b'CREATIVITY AND INNOVATION', b'creativity and innovation'), (b'MANAGEMENT', b'management'), (b'INFORMATION TECHNOLOGY', b'information technology'), (b'OPERATIONS', b'operations'), (b'CONSULTING', b'consulting'), (b'FINANCE', b'finance'), (b'HUMAN RESOURCES', b'human resources'), (b'MANUFACTURING', b'manufacturing')], default=b'', max_length=100, null=True, verbose_name=b'Category')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('cpicture', models.FileField(upload_to=b'', verbose_name=b'Upload Image')),
                ('cjoindate', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Elearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltitle', models.CharField(max_length=250, verbose_name=b'Title')),
                ('ldiscription', models.CharField(max_length=500, verbose_name=b'Description')),
                ('lcategory', models.CharField(choices=[(b'LEARNING AND DEVELOPMENT', b'learning and development'), (b'CONFERENCES', b'conference'), (b'COMMUNICATION', b'communication'), (b'MOTIVATION', b'motivation'), (b'LEADERSHIP', b'leadership'), (b'EDUCATION', b'education'), (b'BUSINESS', b'business'), (b'NETWORKING', b'networking'), (b'ORGANIZATION', b'organization'), (b'MEETUPS', b'meetups'), (b'CREATIVITY AND INNOVATION', b'creativity and innovation'), (b'MANAGEMENT', b'management'), (b'INFORMATION TECHNOLOGY', b'information technology'), (b'OPERATIONS', b'operations'), (b'CONSULTING', b'consulting'), (b'FINANCE', b'finance'), (b'HUMAN RESOURCES', b'human resources'), (b'MANUFACTURING', b'manufacturing')], default=0, max_length=100, verbose_name=b'Category')),
                ('lpicture', models.FileField(upload_to=b'', verbose_name=b'Upload Image')),
                ('lwebsite', models.CharField(default=b'', max_length=300, verbose_name=b'Elearning platform Link')),
                ('lpublish', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Elearningcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000, verbose_name=b'Comment')),
                ('lcommentdate', models.DateTimeField(auto_now=True)),
                ('elearning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Elearning')),
            ],
        ),
        migrations.CreateModel(
            name='Elearningreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000, verbose_name=b'Write Review')),
                ('rating', models.CharField(default=b'', max_length=10, verbose_name=b'Give Rating')),
                ('lreviewdate', models.DateTimeField(auto_now=True)),
                ('elearning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Elearning')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etitle', models.CharField(max_length=250, verbose_name=b'Event Title')),
                ('ecategory', models.CharField(choices=[(b'LEARNING AND DEVELOPMENT', b'learning and development'), (b'CONFERENCES', b'conference'), (b'COMMUNICATION', b'communication'), (b'MOTIVATION', b'motivation'), (b'LEADERSHIP', b'leadership'), (b'EDUCATION', b'education'), (b'BUSINESS', b'business'), (b'NETWORKING', b'networking'), (b'ORGANIZATION', b'organization'), (b'MEETUPS', b'meetups'), (b'CREATIVITY AND INNOVATION', b'creativity and innovation'), (b'MANAGEMENT', b'management'), (b'INFORMATION TECHNOLOGY', b'information technology'), (b'OPERATIONS', b'operations'), (b'CONSULTING', b'consulting'), (b'FINANCE', b'finance'), (b'HUMAN RESOURCES', b'human resources'), (b'MANUFACTURING', b'manufacturing')], default=b'', max_length=100, verbose_name=b'Category')),
                ('esubcategory', models.CharField(choices=[(b'LEARNING AND DEVELOPMENT', b'learning and development'), (b'CONFERENCES', b'conference'), (b'COMMUNICATION', b'communication'), (b'MOTIVATION', b'motivation'), (b'LEADERSHIP', b'leadership'), (b'EDUCATION', b'education'), (b'BUSINESS', b'business'), (b'NETWORKING', b'networking'), (b'ORGANIZATION', b'organization'), (b'MEETUPS', b'meetups'), (b'CREATIVITY AND INNOVATION', b'creativity and innovation'), (b'MANAGEMENT', b'management'), (b'INFORMATION TECHNOLOGY', b'information technology'), (b'OPERATIONS', b'operations'), (b'CONSULTING', b'consulting'), (b'FINANCE', b'finance'), (b'HUMAN RESOURCES', b'human resources'), (b'MANUFACTURING', b'manufacturing')], default=0, max_length=100, verbose_name=b'Sub Category')),
                ('eduration', models.CharField(choices=[(b'SHORT', b'Short'), (b'MEDIUM', b'Medium'), (b'LONG', b'Long')], default=0, max_length=20, verbose_name=b'Event Duration')),
                ('edelivery', models.CharField(choices=[(b'CLASSROOM', b'Classroom'), (b'ONLINE', b'Online')], default=0, max_length=20, verbose_name=b'Event Delivery')),
                ('eventstart', models.DateTimeField(blank=True, null=True, verbose_name=b'Start Date & Time')),
                ('eventend', models.DateTimeField(blank=True, null=True, verbose_name=b'End Date & TIme')),
                ('edescription', models.CharField(default=b'', max_length=500, verbose_name=b'Description')),
                ('ecost', models.IntegerField(default=0, verbose_name=b'Event Cost')),
                ('elocation', models.CharField(max_length=250, verbose_name=b'Location')),
                ('efacebook', models.CharField(default=b'', max_length=300, verbose_name=b'Facebook Link')),
                ('ewebsite', models.CharField(default=b'', max_length=300, verbose_name=b'Website Link')),
                ('epicture', models.FileField(upload_to=b'', verbose_name=b'Upload Image')),
                ('epublish', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Eventcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000, verbose_name=b'Comment')),
                ('ecommentdate', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Eventquery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=1, max_length=100, verbose_name=b'Write Subject')),
                ('message', models.CharField(max_length=1000, verbose_name=b'Write Message')),
                ('equerydate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eventreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000, verbose_name=b'Write Review')),
                ('rating', models.CharField(default=b'', max_length=10, verbose_name=b'Give Rating')),
                ('ereviewdate', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Olocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otitle', models.CharField(max_length=250, verbose_name=b'Title')),
                ('odiscription', models.CharField(max_length=500, verbose_name=b'Description')),
                ('location', models.CharField(max_length=250, verbose_name=b'Location')),
                ('opublish', models.DateTimeField(auto_now=True)),
                ('owebsite', models.CharField(default=b'', max_length=300, verbose_name=b'Website Link')),
                ('opicture', models.FileField(upload_to=b'', verbose_name=b'Upload Image')),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Olocationcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000, verbose_name=b'Comment')),
                ('ocommentdate', models.DateTimeField(auto_now=True)),
                ('olocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Olocation')),
            ],
        ),
        migrations.CreateModel(
            name='Olocationreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000, verbose_name=b'Write Review')),
                ('rating', models.CharField(default=b'', max_length=10, verbose_name=b'Give Rating')),
                ('oreviewdate', models.DateTimeField(auto_now=True)),
                ('olocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Olocation')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name=b'Name')),
                ('mobile', models.IntegerField(default=0, verbose_name=b'Mobile')),
                ('organisation', models.CharField(max_length=250, verbose_name=b'Organisation')),
                ('designation', models.CharField(max_length=500, verbose_name=b'Designation')),
                ('category', models.CharField(choices=[(b'LEARNING AND DEVELOPMENT', b'learning and development'), (b'CONFERENCES', b'conference'), (b'COMMUNICATION', b'communication'), (b'MOTIVATION', b'motivation'), (b'LEADERSHIP', b'leadership'), (b'EDUCATION', b'education'), (b'BUSINESS', b'business'), (b'NETWORKING', b'networking'), (b'ORGANIZATION', b'organization'), (b'MEETUPS', b'meetups'), (b'CREATIVITY AND INNOVATION', b'creativity and innovation'), (b'MANAGEMENT', b'management'), (b'INFORMATION TECHNOLOGY', b'information technology'), (b'OPERATIONS', b'operations'), (b'CONSULTING', b'consulting'), (b'FINANCE', b'finance'), (b'HUMAN RESOURCES', b'human resources'), (b'MANUFACTURING', b'manufacturing')], default=b'', max_length=100, null=True, verbose_name=b'Category')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('picture', models.FileField(upload_to=b'', verbose_name=b'Upload Image')),
                ('joindate', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wtitle', models.CharField(max_length=250, verbose_name=b'Webinar Title')),
                ('wcategory', models.CharField(choices=[(b'LEARNING AND DEVELOPMENT', b'learning and development'), (b'CONFERENCES', b'conference'), (b'COMMUNICATION', b'communication'), (b'MOTIVATION', b'motivation'), (b'LEADERSHIP', b'leadership'), (b'EDUCATION', b'education'), (b'BUSINESS', b'business'), (b'NETWORKING', b'networking'), (b'ORGANIZATION', b'organization'), (b'MEETUPS', b'meetups'), (b'CREATIVITY AND INNOVATION', b'creativity and innovation'), (b'MANAGEMENT', b'management'), (b'INFORMATION TECHNOLOGY', b'information technology'), (b'OPERATIONS', b'operations'), (b'CONSULTING', b'consulting'), (b'FINANCE', b'finance'), (b'HUMAN RESOURCES', b'human resources'), (b'MANUFACTURING', b'manufacturing')], default=0, max_length=100, verbose_name=b'Category')),
                ('webinarstart', models.DateTimeField(blank=True, null=True, verbose_name=b'Start Date & Time')),
                ('webinarend', models.DateTimeField(blank=True, null=True, verbose_name=b'End Date & TIme')),
                ('wdescription', models.CharField(max_length=500, null=True, verbose_name=b'Description')),
                ('wcost', models.IntegerField(default=0, verbose_name=b'Webinar Cost')),
                ('wwebsite', models.CharField(default=b'', max_length=300, verbose_name=b'Website Link')),
                ('wpublish', models.DateTimeField(auto_now=True)),
                ('wpicture', models.FileField(upload_to=b'', verbose_name=b'Upload Image')),
                ('is_favorite', models.BooleanField(default=False)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Webinarcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000, verbose_name=b'Comment')),
                ('wcommentdate', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Webinar')),
            ],
        ),
        migrations.CreateModel(
            name='Webinarreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000, verbose_name=b'Write Review')),
                ('rating', models.CharField(default=b'', max_length=10, verbose_name=b'Give Rating')),
                ('wreviewdate', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Webinar')),
            ],
        ),
        migrations.AddField(
            model_name='webinarcomment',
            name='webinarreview',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainer.Webinarreview'),
        ),
        migrations.AddField(
            model_name='olocationreview',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer'),
        ),
        migrations.AddField(
            model_name='olocationcomment',
            name='olocationreview',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainer.Olocationreview'),
        ),
        migrations.AddField(
            model_name='olocationcomment',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer'),
        ),
        migrations.AddField(
            model_name='olocation',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer'),
        ),
        migrations.AddField(
            model_name='eventreview',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer'),
        ),
        migrations.AddField(
            model_name='eventquery',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer'),
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='eventreview',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainer.Eventreview'),
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer'),
        ),
        migrations.AddField(
            model_name='event',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer'),
        ),
        migrations.AddField(
            model_name='elearningreview',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer'),
        ),
        migrations.AddField(
            model_name='elearningcomment',
            name='elearningreview',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainer.Elearningreview'),
        ),
        migrations.AddField(
            model_name='elearningcomment',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer'),
        ),
        migrations.AddField(
            model_name='elearning',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer'),
        ),
        migrations.AddField(
            model_name='article',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer'),
        ),
    ]
