# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20171208_1551'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventquery',
            new_name='Clientquery',
        ),
    ]
