from django.conf.urls import url

from . import views


app_name = 'trainer'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<trainer_id>\d+)/$', views.details, name='details'),
    url(r'^client/(?P<client_id>\d+)/$', views.client_details, name='client_details'),
    url(r'^(?P<trainer_id>\d+)/webinar_details/(?P<webinar_id>\d+)/$', views.wdetails, name='wdetails'),
    url(r'^(?P<trainer_id>\d+)/article_details/(?P<article_id>\d+)/$', views.adetails, name='adetails'),
    url(r'^(?P<trainer_id>\d+)/elearning_details/(?P<elearning_id>\d+)/$', views.ldetails, name='ldetails'),
    url(r'^(?P<trainer_id>\d+)/location_details/(?P<olocation_id>\d+)/$', views.odetails, name='odetails'),
    url(r'^(?P<event_id>\d+)/favorite/$', views.favorite, name='favorite'),
    url(r'^(?P<webinar_id>\d+)/favorite_webinar/$', views.favorite_webinar, name='favorite_webinar'),
    url(r'^(?P<article_id>\d+)/favorite_article/$', views.favorite_article, name='favorite_article'),
    url(r'^(?P<elearning_id>\d+)/favorite_elearning/$', views.favorite_elearning, name='favorite_elearning'),
    url(r'^(?P<olocation_id>\d+)/favorite_olocation/$', views.favorite_olocation, name='favorite_olocation'),
    url(r'^events/(?P<filter_by>[a-zA_Z]+)/$', views.events, name='events'),
    url(r'^webinars/(?P<filter_by>[a-zA_Z]+)/$', views.webinars, name='webinars'),
    url(r'^articles/(?P<filter_by>[a-zA_Z]+)/$', views.articles, name='articles'),
    url(r'^elearnings/(?P<filter_by>[a-zA_Z]+)/$', views.elearnings, name='elearnings'),
    url(r'^olocations/(?P<filter_by>[a-zA_Z]+)/$', views.olocations, name='olocations'),
    url(r'^create_trainer/$', views.create_trainer, name='create_trainer'),
    url(r'^create_client/$', views.create_client, name='create_client'),
    url(r'^(?P<trainer_id>\d+)/create_event/$', views.create_event, name='create_event'),
    url(r'^(?P<trainer_id>\d+)/create_webinar/$', views.create_webinar, name='create_webinar'),
    url(r'^(?P<trainer_id>\d+)/create_article/$', views.create_article, name='create_article'),
    url(r'^(?P<trainer_id>\d+)/create_elearning/$', views.create_elearning, name='create_elearning'),
    url(r'^(?P<trainer_id>\d+)/create_olocation/$', views.create_olocation, name='create_olocation'),
    url(r'^(?P<trainer_id>\d+)/delete_event/(?P<event_id>\d+)/$', views.delete_event, name='delete_event'),
    url(r'^(?P<trainer_id>\d+)/delete_webinar/(?P<webinar_id>\d+)/$', views.delete_webinar, name='delete_webinar'),
    url(r'^(?P<trainer_id>\d+)/delete_article/(?P<article_id>\d+)/$', views.delete_article, name='delete_article'),
    url(r'^(?P<trainer_id>\d+)/delete_elearning/(?P<elearning_id>\d+)/$', views.delete_elearning, name='delete_elearning'),
    url(r'^(?P<trainer_id>\d+)/delete_olocation/(?P<olocation_id>\d+)/$', views.delete_olocation, name='delete_olocation'),
    url(r'^(?P<trainer_id>\d+)/favorite_trainer/$', views.favorite_trainer, name='favorite_trainer'),
    url(r'^(?P<trainer_id>\d+)/delete_trainer/$', views.delete_trainer, name='delete_trainer'),
    url(r'^(?P<client_id>\d+)/delete_client/$', views.delete_client, name='delete_client'),
    url(r'^trainer-update/(?P<pk>\d+)/$', views.TrainerUpdate.as_view(), name='trainer_update'),
    url(r'^client-update/(?P<pk>\d+)/$', views.ClientUpdate.as_view(), name='client_update'),
    url(r'^(?P<trainer_id>\d+)/event-update/(?P<pk>\d+)/$', views.EventUpdate.as_view(), name='event_update'),
    url(r'^(?P<trainer_id>\d+)/webinar-update/(?P<pk>\d+)/$', views.WebinarUpdate.as_view(), name='webinar_update'),
    url(r'^(?P<trainer_id>\d+)/article-update/(?P<pk>\d+)/$', views.ArticleUpdate.as_view(), name='article_update'),
    url(r'^(?P<trainer_id>\d+)/elearning-update/(?P<pk>\d+)/$', views.ElearningUpdate.as_view(), name='elearning_update'),
    url(r'^(?P<trainer_id>\d+)/location-update/(?P<pk>\d+)/$', views.LocationUpdate.as_view(), name='location_update'),
    url(r'^(?P<trainer_id>\d+)/review_details/(?P<event_id>\d+)/$', views.review_details, name='review_details'),
    url(r'^(?P<trainer_id>\d+)/event_details/(?P<event_id>\d+)/$', views.edetails, name='edetails'),
    url(r'^(?P<trainer_id>\d+)/review_comment/(?P<event_id>\d+)/(?P<eventreview_id>\d+)/$', views.review_comment, name='review_comment'),
    url(r'^(?P<trainer_id>\d+)/client_query/$', views.client_query, name='client_query'),
    url(r'^(?P<trainer_id>\d+)/delete_query/(?P<eventquery_id>\d+)/$', views.delete_query, name='delete_query'),
    url(r'^(?P<trainer_id>\d+)/review_webinar/(?P<webinar_id>\d+)/$', views.review_webinar, name='review_webinar'),
    url(r'^(?P<trainer_id>\d+)/comment_webinar/(?P<webinar_id>\d+)/(?P<webinarreview_id>\d+)/$', views.comment_webinar, name='comment_webinar'),
    url(r'^(?P<trainer_id>\d+)/review_olocation/(?P<olocation_id>\d+)/$', views.review_olocation, name='review_olocation'),
    url(r'^(?P<trainer_id>\d+)/comment_olocation/(?P<olocation_id>\d+)/(?P<olocationreview_id>\d+)/$', views.comment_olocation, name='comment_olocation'),
    url(r'^(?P<trainer_id>\d+)/review_elearning/(?P<elearning_id>\d+)/$', views.review_elearning, name='review_elearning'),
    url(r'^(?P<trainer_id>\d+)/comment_elearning/(?P<elearning_id>\d+)/(?P<elearningreview_id>\d+)/$', views.comment_elearning, name='comment_elearning'),
    url(r'^search/$', views.search, name='search'),
    url(r'^eventsearch/$', views.eventsearch, name='eventsearch'),
    url(r'^trainersearch/$', views.trainersearch, name='trainersearch'),
    url(r'^webinarsearch/$', views.webinarsearch, name='webinarsearch'),
    url(r'^elearningsearch/$', views.elearningsearch, name='elearningsearch'),
    url(r'^olocationsearch/$', views.olocationsearch, name='olocationsearch'),




]